# Generated by Django 5.0.2 on 2024-02-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menuitem_image_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
