# Generated by Django 5.0.2 on 2024-02-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_menuitem_is_offer_menuitem_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
