# Generated by Django 5.0.2 on 2024-02-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_menuitem_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
